CREATE TABLE IF NOT EXISTS TB_EXPENSE (
	ID bigserial NOT NULL PRIMARY KEY,
	PERSON_NAME varchar(100) NOT NULL,
	DESCRIPTION varchar(300) NOT NULL,
	AMOUNT numeric(19,4) NOT NULL,
	TAGS varchar(100) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

INSERT INTO TB_EXPENSE (ID, PERSON_NAME, DESCRIPTION, AMOUNT, TAGS, CREATED_DATE, UPDATED_DATE) VALUES (200, 'MARCELO ALVES', 'CONTA DE LUZ', 100.00, 'GASTO CASA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_EXPENSE (ID, PERSON_NAME, DESCRIPTION, AMOUNT, TAGS, CREATED_DATE, UPDATED_DATE) VALUES (201, 'JURANDIR ALVES', 'CONTA DE AGUA',  200.00, 'GASTO CASA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_EXPENSE (ID, PERSON_NAME, DESCRIPTION, AMOUNT, TAGS, CREATED_DATE, UPDATED_DATE) VALUES (202, 'CLAUDIO ALVES', 'CONTA DE ESGOTO', 300.00, 'GASTO CASA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_EXPENSE (ID, PERSON_NAME, DESCRIPTION, AMOUNT, TAGS, CREATED_DATE, UPDATED_DATE) VALUES (203, 'JOSÉ ALVES', 'CONTA - OUTROS', 400.00, 'GASTO CASA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
